### PR TITLE
removed graphs

### PR DESCRIPTION
**Pull request by dhe95**
at least we still have randomly blinking dots

### CODE REVIEW

**Comment by awli** [comment]
what about the random Angular directives?

**Comment by dhe95** [comment]
?

**Comment by awli** [comment]
like .directive('draggable')

in widget.coffee

**Comment by dhe95** [comment]
are we removing all the widget stuff entirely or just the graphs?

**Comment by awli** [comment]
idk, I guess you can make the call. the point is to remove the code that we can't use effectively.

**Comment by dhe95** [comment]
It would probably be better to start over with how we do widgets. Also I'm not sure why but the sensors won't auto update anymore.

**Comment by awli** [comment]
Yeah, starting over seems to make more sense.



--

Allen LiAdvisor, Pioneers in Engineering

(805) 768-4191 | allen@pioneers.berkeley.edu

http://pioneers.berkeley.edu

**Pull request merged**
