### PR TITLE
Peripheral names cannot have spaces or backslashes

### PR DESCRIPTION
**Pull request by mud13**

### CODE REVIEW

**Comment by AllanYangZhou** [comment]
Good start! Tagging @aakashnshah @nfong so you guys see this.

I would suggest that you use RegEx instead of iterating through the characters. See [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) for how to use RegEx's in Javascript. You can write a RegEx and just test the string with it.

**Comment by AllanYangZhou** [comment]
The RegExp I suggest you use to test is `^[A-Za-z0-9]+$`. This should prevent spaces, backslashes, and other non-alphanumeric characters.

**Comment by nikitakit** [comment]
If you're checking Python ids, you can be more pedantic and use ```[A-Za-z][A-Za-z0-9]*```. This catches the case of starting with a digit, which is not allowed. Sadly, that still leaves clashes with some reserved keywords.

**Comment by AllanYangZhou** [comment]
Updated work now available in: https://github.com/pioneers/daemon/pull/125

**Pull request closed without merging**
