### PR TITLE
Basic Upload Tar Functionality

### PR DESCRIPTION
**Pull request by kevinmasd**
Adds a Button to Toolbar to specify what file should be chosen and sends it to Ansible. Currently hardcoded only to deal with tar files.

### CODE REVIEW

**Comment by vdonato** [comment]
A few notes about the .tar upload feature:
-   The updates are compressed into .tar.gz files, so that'll need to be changed a bit.
-   Also, students will need to upload two files. One of the files will be the update itself (the .tar.gz file), and the other will be a signature for security reasons (has file extension .tar.gz.asc)

**Comment by kevinmasd** [comment]
Currently, this feature just looks for files whose name has "tar" in it, so both .tar.gz and .tar.gz.asc files should be fine (along with tar.txt ...); multiple uploads also work. The only issue is that this system doesn't tell you if you are overwriting over an existing file.

**Comment by AllanYangZhou** [comment]
Thanks!

It appears something went wrong with your fork's git commit history. For example, you have changes to your `.travis.yml` which aren't related. Also, you have commits related to the gamepad/etc which aren't related. Can you fix those before I merge it in?

**Comment by kevinmasd** [comment]
Most of those gamepad changes were reverted in later commits (i.e. Negative motor values). `.travis.yml` was modified so Travis CI doesn't fail on every build afterwards, given how much Dawn has changed in these few months.

**Comment by AllanYangZhou** [comment]
Oh I see. Looks good then!

**Pull request merged**
